### ISSUE TITLE
Weird erro failed: 256 at ./run-trust4 line 48.

### ISSUE THREAD

**Issue by Cinade** [liulab-dfci/TRUST4#127]
Hello
I downloaded and installed TRUST4 on Linux using git clone

However when I start the run with this command on top of the image

The run start but I get the following error, cant resolve it:

(base) fpadonou@nic5-login1 ~/TRUST4 $ ./run-trust4 --od ./NormalTissueTS -o run1  -b Bamfile/mergedTSNTissue.bam -f hg38_bcrtcr.fa --ref human_IMGT+C.fa
[Wed May  4 16:57:49 2022] TRUST4 begins.
[Wed May  4 16:57:49 2022] SYSTEM CALL: /home/users/f/p/fpadonou/TRUST4/bam-extractor -b Bamfile/mergedTSNTissue.bam -t 1 -f hg38_bcrtcr.fa -o ./NormalTissueTS/run1_toassemble
[Wed May  4 16:57:49 2022] Start to extract candidate reads from bam file.
[Wed May  4 17:04:14 2022] Finish obtaining the candidate read ids.
[Wed May  4 17:06:01 2022] Finish extracting reads.
[Wed May  4 17:06:01 2022] SYSTEM CALL: /home/users/f/p/fpadonou/TRUST4/trust4  -f hg38_bcrtcr.fa -o ./NormalTissueTS/run1 -1 ./NormalTissueTS/run1_toassemble_1.fq -2 ./NormalTissueTS/run1_toassemble_2.fq
[Wed May  4 17:06:01 2022] SYSTEM CALL: /home/users/f/p/fpadonou/TRUST4/annotator -f human_IMGT+C.fa -a ./NormalTissueTS/run1_final.out -t 1 -o ./NormalTissueTS/run1  -r ./NormalTissueTS/run1_assembled_reads.fa > ./NormalTissueTS/run1_annot.fa
Need to use -a to specify the assembly file.
system /home/users/f/p/fpadonou/TRUST4/annotator -f human_IMGT+C.fa -a ./NormalTissueTS/run1_final.out -t 1 -o ./NormalTissueTS/run1  -r ./NormalTissueTS/run1_assembled_reads.fa > ./NormalTissueTS/run1_annot.fa failed: 256 at ./run-trust4 line 48.
(base) fpadonou@nic5-login1 ~/TRUST4 $

See picture below.

Could you please help me?
![Capture](https://user-images.githubusercontent.com/104915885/166712159-1af6d619-c350-4c24-8587-994b8628ebbd.PNG)

Thank yu very much.

**Comment by mourisl** [comment]
I think TRUST4 fails to find any TCR/BCR reads in the sample, and generate empty files which causes this error. This could happen when the immune infiltration level is very low in the sample. I will update the program later to properly throw this "error".

**Comment by Cinade** [comment]
Thank you for your answer. the samples are from normal breast tissues so I will try again on breast tumors.
Thanks

**Comment by Cinade** [comment]
Well
I run the comand with all my bam files and none of them worked.
I opted for the fastqc files and it worked, although i have another issue. The report file and airr file are empty.
What does it mean for my results?

**Comment by mourisl** [comment]
I think TRUST4 only found some V o C gene fragmented contigs, and no CDR3 information in that case. Just want to confirm, is this human data, and how many reads are in each file?  Thank you.

**Comment by Cinade** [comment]
Thank you for yor answer
Its human data, cancer
I dont really know the number of reads in each file.
I used an old fastq file to test it out.

**Comment by Cinade** [comment]
Hello
So TRUST4 wroked with some of my samples but I got a new error.
See the image below. Thank you for your help.
![trust](https://user-images.githubusercontent.com/104915885/178784199-2ac1dada-b0e2-4979-9294-419ed8ed2d99.jpg)

**Comment by mourisl** [comment]
Are the toassemble files for that sample empty?

**Comment by Cinade** [comment]
Hello
Apologies for the delay. I was very sick.

Here's a few line from Assemble_1.fq:

@A00801:196:H7TC5DSX3:4:1101:21739:1877
GGCCATGGGAGGTTCTTGGTGATCTTGGCCTCTGCAGCCTCAGGGGGGTGGCCTGGCTGGGAGCTGGAGGGGAGTGGGCCAAGGAGGAGAGGGGTAGGAACCAGTGGAGGTGGTTGGGGAAGCAAAGGTTGACAGCCACGTTGGTACCCGG
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFF:FFFFF
@A00801:196:H7TC5DSX3:4:1101:25310:1892
CAGGGGTAGATGTGGTGCCACACTAGAATCAAAGTAAGGGGGATGAACCTGACCAGCCCAACTAAAGCCAAAAGCCTCAAAGTTCTGCAAAACTAAGAAAAATGAGATAGAGCATGCAGCCTGCAGTGCCGGTTGCCAACA
+
FFFFFFFFFFFFFFFFFFFFFFFF::FFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF:FFFFFFFFFFFFFF:FFFFFFFFF:FFFFF,FFFFFFFFFFFFFFFFFFFFFFFFF:FFFF,FF
@A00801:196:H7TC5DSX3:4:1101:14534:2206
CCCCCACTAACAAAATTTAAAGCTTCTGTATTTTAAGAAGTTATAGATATGTAATATTTTGAGTGAATACCTTCTATTTTAAAAAAGCCCTTAACTGTTTTTAATGCTCTGAGATTAAAGGAGAAGAGGGGATAACCCCGAATTAGCATA
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFF
@A00801:196:H7TC5DSX3:4:1101:17924:2503
TCAGGGGCATTCTTTCCAGTTATCCCGAGCATTCGGCATCATTCATGAAATTCTATGTTTCCAGGTCTCTGTGCTCTGGCTGTGCTAACTCAGCCCCCGTCTGCATCTGCCTCACTGGGAGCCTCAGTGCCGGTCTATGTCA
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFF,FFFFFFFFF:FFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@A00801:196:H7TC5DSX3:4:1101:9055:2644
CCGGCTGCCCATTGCTCTCCCACTCCACGGCGATGTCGCTGGGATAGAAGCCTTTGACCAGGCAGGTCAGGCTGACCTGGTTCTTGGTCATCTCCTCCCGGGATGGGGGCAGGGTGTACACCTGTGGTTCTCGGGGCTGCCCCCCGGTACG
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF
@A00801:196:H7TC5DSX3:4:1101:11080:3427
TCCCCTCAAATACCCCATCGAAGCCCTTCAACTTTAGCAGATCATAATTTGCATCTACTTTTTTAACGAAAGAGAGAGCAGGCAACATGTCCTTTACTGCCTCTACCCTGAATTTCTTCAGATGGCTAAAGAGGAACGCGGTTATACT
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFF
@A00801:196:H7TC5DSX3:4:1101:12744:3897
GGTGACACAATTTGCTGTCTCTCTAAAAAAAAAAGAAGAAGAAGAAAAGGAGAAAGAGAGAGAGGTTCATACTCCAATGGCTGTAAAGGATAAGGAGCCCGGTGATCATCA


And here's a few line for Assemble_2.fq:



@A00801:196:H7TC5DSX3:4:1101:21739:1877
TAGTTTGTACCGGGTACCAACGTGGCTGTCAACCTTTGCTTCCCCAACCACCTCCACTGGTTCCTACCCCTCTCCTCCTTGGCCCACTCCCCTCCAGCTCCCAGCCAGGCCACCCCCCTGAGGCTGCAGAGGCCAAGATCACCAAGAAC
+
FFFFFFF::,F,:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFF:FF:FFFFFFFFFFFF:FFFFFFFFFFFFFF
@A00801:196:H7TC5DSX3:4:1101:25310:1892
TGTTGGCAGGTGGCACTGCAGGCTGCATGCTCTATCTCATTTTTCTTAGTTTTGCAGAACTTTGAGGCTTTTGGCTTTAGTTGGGCTGGTCAGGTTCATCCCCCTTACTTTGATTCTAGTGTGGCACCACATCTACCCCTG
+
F,,FF:FF:FF,,FFFFFFF:FFFFFFFFF:FFFFFFFFFFFFFFFFFF:FFFFFF:FFFF,FFFF:FFFFFFFFFFFFFFFFFFFF:FFF,FFF:FF:FFFFFFF:::FFFFFFFFFFFFF:FFFFFFFF:FFFF:F:,F
@A00801:196:H7TC5DSX3:4:1101:14534:2206
TTCTGGTCAACTTGGGTACTAGCTGTTCTGTAGAATTTTGAAAGAAATCCTTCTCCTAGCAAAGACTGTAAGAGGGCTTTGTATGCTAATTCGGGGTTATCCCCTCTTCTCCTTTAATCTCAGAGCATTAAAAACAGTTAAGGGCTTTTTT
+
FFFFFFFFF,,,,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFF
@A00801:196:H7TC5DSX3:4:1101:17924:2503
TGACATAGACAGGCACTGAGGCTCCCAGTGAGGCAGATGCAGACGGGGGCTGAGTTAGCACAGCCAGAGCACAGAGACCTGGAAACATAGAATTTCATGAATGATGCCGAATGCTCGGGATAACTGGAAAGAATGCCCCTGA
+
FFFFFFFF:,,,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@A00801:196:H7TC5DSX3:4:1101:9055:2644
CTTATCGTAGCTGGGGGCAGCCCCGAGAACCACAGGTGTACACCCTGCCCCCATCCCGGGAGGAGATGACCAAGAACCAGGTCAGCCTGACCTGCCTGGTCAAAGGCTTCTATCCCAGCGACATCGCCGTGGAGTGGGAGAGCAATGGGC
+
FFFFFFFF,,:,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF
@A00801:196:H7TC5DSX3:4:1101:11080:3427
CTAGTATAAACTCGTTCCTCTTTAGCCATCTGAAGAAATTCAGGGTAGAGGCAGTAAAGGACATGTTGCCTGCTCTCTCTTTCGTTAAAAAAGTAGATGCAAATTATGATCTGCTAAAGTTGAAGGGCTTCGATGGGGTATTTGAGGGGA
+
FFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF:FFFFFFFFFFFFFFFFFFFFF
@A00801:196:H7TC5DSX3:4:1101:12744:3897
TGATGATCACCGGGCTCCTTATCCTTTACAGCCATTGGAGTATGAACCTCTCTCTCTTTCTCCTTTTCTTCTTCTTCTTTTTTTTTTAGAGAGACAGCAAATTGTGTCACC

**Comment by Cinade** [comment]
For another sample fastq, I get the following error. Which is weird because I do have the latest version of Trust4.
Thank you very much for your help. I am runing multiple samples and while some work I have some issues with other.
I attach the image error and also the size of each fastq file in KB.
![Capture1](https://user-images.githubusercontent.com/104915885/180987085-b9cd9dc6-fbad-42b9-a4e9-c610e145c0d2.PNG)
![Capture21](https://user-images.githubusercontent.com/104915885/180987089-e569b9a1-5c14-4c0b-9bd8-3f009530b5e3.PNG)

**Comment by mourisl** [comment]
Thank you for sharing the information. I will look into the first issue. For the second issue, it seems you missed the "-2" option for the second read (XXX_R2_001.fastq). As a result, both files are fed to read 1, and read 2 has empty reads causing the "different number of reads" error.

**Comment by Cinade** [comment]
Thank you very much. Let me know if you find something for the first issue.

**Comment by karthikram-takara** [comment]
Hi @mourisl, I am running into the same error as the original ticket specified (the one with -a) because the input fastqs do not have any TCR/BCR reads. Has there been an update to fix this issue? I am using version 1.0.4. Thanks.

**Comment by mourisl** [comment]
The missing TCR/BCR reads might be due to too few T/B cells infiltrating your sample. This could be due to biological reasons, and TRUST4 can not fix that. I have fixed several things in the current github repo, so TRUST4 at least won't crash if there is no candidate reads can be found in the next release.

**Comment by karthikram-takara** [comment]
Thank you @mourisl. I agree that the issue is biological. After updating to 1.0.13, I get a different error, but the analysis still fails. Is the new release coming up soon?

**Comment by mourisl** [comment]
Yes, I'm waiting for some information on other issues. When those are addressed, I will draft a new release.

**Comment by karthikram-takara** [comment]
Great, thanks for the update!
