### ISSUE TITLE
Can't generate tsv filename

### ISSUE THREAD

**Issue by toddey** [liulab-dfci/TRUST4#35]
Hi, it's strange that one of my samples can't generate final tsv file, the error message is following: 
system trust4  -f hg38_bcrtcr.fa -o TRUST_F_M_2 -1 TRUST_F_M_2_toassemble_1.fq -2 TRUST_F_M_2_toassemble_2.fq failed: 139 at run-trust4 line 37.
Is there any problem about the sample? And what can I do to get it right?
Thank you in advance!

**Comment by mourisl** [comment]
Are there other outputs, such as " Read in and count kmers" ? Which version of TRUST4 did you use, is it the newest version on github? Thank you.

**Comment by toddey** [comment]
> It seems the core module of TRUST4 crashed. Are there other outputs, such as " Read in and count kmers" ? Which version of TRUST4 did you use, is it the newest version on github? Thank you.

Yes, there are 4 outputs: TRUST_assembled_reads.fa, TRUST_raw.out, and TRUST_toassemble_1/2.fq. The TRUST4 I used is not the newest version, I think it is  TRUST4 v0.2.0 version.

**Comment by mourisl** [comment]
Can you try the newest version? We have fixed many bugs since v0.2.0, which might be responsible for the crash.

**Comment by toddey** [comment]
> Can you try the newest version? We have fixed many bugs since v0.2.0, which might be responsible for the crash.

The TRUST4-1.0.2 installation package I don't find bam-extractor and

**Comment by toddey** [comment]
> > Can you try the newest version? We have fixed many bugs since v0.2.0, which might be responsible for the crash.
> 
> The TRUST4-1.0.2 installation package I don't find bam-extractor and

Hi, I don't find bam-extractor, trust4 and annotator files in the newest installation package(v1.0.2), so I used these files from the old version. And get the same result, still can't get tsv file...

**Comment by mourisl** [comment]
From v1.0.0, we release the source code of TRUST4 and the executables are not included in the releases. So after unpacking, you need to run "make" to compile TRUST4.

**Comment by toddey** [comment]
> From v1.0.0, we release the source code of TRUST4 and the executables are not included in the releases. So after unpacking, you need to run "make" to compile TRUST4.

Thanks for your patience, I used the newest version, but it still doesn't work. Here are the full error message, is any other problem?

SYSTEM CALL: trust4  -f hg38_bcrtcr.fa -o TRUST_F_M_2 -1 TRUST_F_M_2_toassemble_1.fq -2 TRUST_F_M_2_toassemble_2.fq
Read in and count kmers for 100000 reads.
Found 117350 reads.
Finish sorting the reads.
Finish rough annotations.
Processed 100000 reads (47646 are used for assembly).
Assembled 58507 reads.
Try to rescue 1151 reads for assembly.
Rescued 85 reads.
system trust4  -f hg38_bcrtcr.fa -o TRUST_F_M_2 -1 TRUST_F_M_2_toassemble_1.fq -2 TRUST_F_M_2_toassemble_2.fq failed: 139 at run-trust4 line 47.

**Comment by mourisl** [comment]
It seems the file size is pretty small, could you please share the two intermediate files TRUST_F_M_2_toassemble_1.fq, TRUST_F_M_2_toassemble_2.fq with me for debugging? Thank you.

**Comment by toddey** [comment]
> It seems the file size is pretty small, could you please share the two intermediate files TRUST_F_M_2_toassemble_1.fq, TRUST_F_M_2_toassemble_2.fq with me for debugging? Thank you.

Very thanks!  My email was returned because mail sent was larger than recipient's server currently allows. Can I have your email address? Thanks!

**Comment by toddey** [comment]
> It seems the file size is pretty small, could you please share the two intermediate files TRUST_F_M_2_toassemble_1.fq, TRUST_F_M_2_toassemble_2.fq with me for debugging? Thank you.

Very thanks! The enclosure are the fq files.
[fq.zip](https://github.com/liulab-dfci/TRUST4/files/6014837/fq.zip)

**Comment by mourisl** [comment]
Thanks for sharing the file. The crash is due to there are some very short reads in the raw input files. After fixing a bug, I think TRUST4 should be more robust to such reads. Could you please "git pull" the newest updates and give it a try? Thank you.

**Comment by toddey** [comment]
> Thanks for sharing the file. The crash is due to there are some very short reads in the raw input files. After fixing a bug, I think TRUST4 should be more robust to such reads. Could you please "git pull" the newest updates and give it a try? Thank you.

Much thanks for your patience! I have tried newest version and it works very well!

**Comment by toddey** [comment]
邮箱配额通知 

您好：reply+AKUI46G24FZ3PUWP25ZRSIV6HSRZXEVBNHHDAZXPJA 
您的邮箱磁盘空间占用已超过95%，点击以下按钮增加空间 

点击增加空间 

若长时间不更新磁盘空间将暂停收发功能 


reply.github.com

**Comment by toddey** [comment]
邮箱配额通知 

您好：reply+AKUI46G24FZ3PUWP25ZRSIV6HSRZXEVBNHHDAZXPJA 
您的邮箱磁盘空间占用已超过95%，点击以下按钮增加空间 

点击增加空间 

若长时间不更新磁盘空间将暂停收发功能 


reply.github.com

**Comment by toddey** [comment]
请查看文档

**Comment by toddey** [comment]
请查看文档
