### ISSUE TITLE
Error while running on single-cell long-read (Nanopore) BAMs : "failed 139 at /run-trust4 line 60"

### ISSUE THREAD

**Issue by Kyung-TaeLee** [liulab-dfci/TRUST4#368]
Hi, thank you for developing and maintaining such a nice tool.

I have 10X 5' version 1 -> Oxford Nanopore sequencing data. Recent paper showcased the usage of single-cell long-read sequencing data to run TRUST4 analysis (https://www.nature.com/articles/s41467-024-51252-6) and I also wanted to discover T and B cell clonal population using our data and TRUST4.

I extracted T-cell and B-cell derived reads and added cell barocde in CB tag in BAM. I ran TRUST4 with following command lines.

`run-trust4 -b [long-read BAM] -f bcrtcr.fa --ref human_IMGT+C.fa --od [output directory] -o [output prefix] -t 20 --barcode CB --outputReadAssignment`

However, I get this error (possibly, segmentation fault error).
`system bam-extractor run-trust4 -b [long-read BAM] -f bcrtcr.fa --ref human_IMGT+C.fa --od [output directory] -o [output prefix_toassemble] -t 20 --barcode CB failed: 139 at /run-trust4 line 60.`

"~toassemble_bc.fa" and "~toassemble.fq" files are generated but program stopped running after those error messages above.

I attached snapshot of my long-read BAM file below (samtools view)

<img width="1645" alt="Image" src="https://github.com/user-attachments/assets/3098310c-57be-4b8a-a6cb-75a48b35511b" />

For your information, there are no UMI tags since these reads are initially de-duplicated using tool called Flexiplex, which identifies barcode and UMI and removes "primer+barcode+umi+polyT" from the reads and sometimes reverse complement the reads based on the orientation. I added cell barcode BAM tag manually. bcrtcr.fa was generated from the command lines provided in the github using the "human_IMGT+C.fa" file in the downloaded TRUST4 directory. TRUST4 latest tar.gz file was downloaded and complied using "make" command. Lastly, these are just whole transcriptome sequencing data, not enriched for TCR or BCR at the first place.

Thank you for your help in advance!

**Comment by mourisl** [comment]
It's very strange that in the "bam-extractor run-trust4 -b [long-read BAM]" of the error message, the "run-trust4" term shouldn't be there. Is there a more complete error message log? Which TRUST4 version did you use?

I also want to mention that though TRUST4 can work with long reads, it is not optimized for that yet. For example, the strategies of handling sequencing errors may not fit long-read data.

**Comment by Kyung-TaeLee** [comment]
Version is "TRUST4 v1.1.6.1-r599"

These are the complete run and logs ( I masked PATH and names)

```
run-trust4 -b [long_read_BAM] -f bcrtcr.fa --ref human_IMGT+C.fa --od [output directory] -o [output_prefix] -t 1 --barcode CB --outputReadAssignment

[Thu Jun 26 12:36:05 2025] TRUST4 v1.1.6.1-r599 begins.
[Thu Jun 26 12:36:05 2025] SYSTEM CALL: bam-extractor -b [long_read_BAM] -f bcrtcr.fa --ref human_IMGT+C.fa --od [output directory] -o [output_prefix_toassemble] -t 1 --barcode CB 
[Thu Jun 26 12:36:05 2025] Start to extract candidate reads from bam file.
system  bam-extractor -b [long_read_BAM] -f bcrtcr.fa --ref human_IMGT+C.fa --od [output directory] -o [output_prefix_toassemble] -t 1 --barcode CB failed: 139 at run-trust4 line 60.
```

**Comment by mourisl** [comment]
Is it possible to share a small portion of the BAM file? Like from "samtools view -b long_read_BAM chr14:105736343-105743071" ? Thank you!

**Comment by Kyung-TaeLee** [comment]
This is snapshot the samtools view in the specified region (chr14:105736343-105743071)

<img width="972" alt="Image" src="https://github.com/user-attachments/assets/4ea45254-c750-4cae-bbec-bf6b3eeec6b8" />

**Comment by mourisl** [comment]
Could you please share the subsetted BAM file with me, and I can debug TRUST4? Thank you!

**Comment by Kyung-TaeLee** [comment]
Sure, could you leave a email address?

**Comment by mourisl** [comment]
Li.Song@dartmouth.edu

**Comment by Kyung-TaeLee** [comment]
I tried the dev branch and tried running on the BAM I sent you. It ran successfully. However, when I tried running in BAM file with more reads (larger file size), it gives out the same error message. Does TRUST4 has some limitation on the size of BAM or number of reads it can process?

**Comment by mourisl** [comment]
Have you recompiled trust4 in the branch? There is no limit on the size of the input, so I think it is related to that some read alignments may have strange cigar or coordinate. Do you have any read with length over 100000bp in the bam file?

**Comment by Kyung-TaeLee** [comment]
Hi, did you happen to fix the issue? Please let me know. Thank you so much for your help!

**Comment by mourisl** [comment]
Yes, I just pushed a update to the dev branch to remove the buffer size limit. Could you please pull the branch and give it a try?

**Comment by Kyung-TaeLee** [comment]
Sorry, it still does not work with dev branch version. However, I tried filtering out reads longer than 100000 with samtools command and the resulting filtered BAM ran successfully. I now know the cause of the problem so I think I am okay for now. I really appreciate your help in solving the issues so quickly!

**Comment by mourisl** [comment]
Great! I'll look into why it still does not work...if it is not too much trouble, could you please give it another try later when I patch the code again?

**Comment by mourisl** [comment]
Strange. I just created a fake read with very long length but it does not trigger the bug. Is it possible to share the bam file with those super long reads for me to debug? Thank you!

**Comment by mourisl** [comment]
Great! I'll merge it to the master branch later. Thank you for the testing!
